version: '3.9'

services:
  app:
    build: .
    container_name: VideoOverflow
    ports:
      - "80:80"
      - "443:443"
    environment:
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_URLS: "http://+:80;https://+:443"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "Test1234"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/cert.pfx"
      ConnectionString_VideoOverflow: "Server=db;Database=VideoOverflow;UserId=postgres;Password=Test1234"
    depends_on:
      - db
    
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: Test1234
      POSTGRES_DB: VideoOverflow