using System;
using System.Linq;
using VideoOverflow.Infrastructure.Entities;

namespace VideoOverflow.Infrastructure.Tests;

public class CommentRepositoryTests
{

    private readonly VideoOverflowContext _context;
    private readonly CommentRepository _repo;
    public CommentRepositoryTests()
    {
        var repo = new RepositoryTestsSetup();
        _context = repo.Context;
        
        _repo = new CommentRepository(_context);
    }
    
    [Fact]
    public async Task GetAll_Returns_All_Comments_With_Creator()
    {

        var user1 = new User() {Id = 1, Name = "OndFisk", Comments = new Collection<Comment>()};
        var user2 = new User() {Id = 2, Name = "SødFisk",  Comments = new Collection<Comment>()};

        
        var f = _context.Users.Add(user1); 
        var g = _context.Users.Add(user2);
        

        var user1Comment1 = new CommentCreateDTO() {CreatedBy = f.Entity.Id, Content = "This docker tutorial is smooth"};
        var user1Comment2 = new CommentCreateDTO() {CreatedBy = f.Entity.Id, Content = "Very helpful guide for beginners!"};
        
        var user2Comment1 = new CommentCreateDTO() {CreatedBy = g.Entity.Id, Content = "Indeed"};
        var user2Comment2 = new CommentCreateDTO() {CreatedBy = g.Entity.Id, Content = "Thank you very much!"};
        
        
        await _repo.Push(user1Comment1);
        await _repo.Push(user1Comment2);
        await _repo.Push(user2Comment1);
        await _repo.Push(user2Comment2);
        

        var comments = await _repo.GetAll();

        Assert.Collection(comments, comment => Assert.Equal(new CommentDTO(1, 1, 0,"This docker tutorial is smooth"), comment),
            comment => Assert.Equal(new CommentDTO(2, 1, 0,"Very helpful guide for beginners!"), comment),
            comment => Assert.Equal(new CommentDTO(3, 2, 0,"Indeed"), comment),
            comment => Assert.Equal(new CommentDTO(4, 2, 0,"Thank you very much!"), comment));
    }
    
    [Fact]
    public async Task GetAll_Returns_All_Comments_Without_Creator()
    {
        
        var comment1 = new CommentCreateDTO() {Content = "This docker tutorial is smooth"};
        var comment2 = new CommentCreateDTO() {Content = "Very helpful guide for beginners!"};
        
        var comment3 = new CommentCreateDTO() {Content = "Indeed"};
        var comment4 = new CommentCreateDTO() {Content = "Thank you very much!"};
        
        
        await _repo.Push(comment1);
        await _repo.Push(comment2);
        await _repo.Push(comment3);
        await _repo.Push(comment4);
        

        var comments = await _repo.GetAll();

        Assert.Collection(comments, comment => Assert.Equal(new CommentDTO(1, 0, 0,"This docker tutorial is smooth"), comment),
            comment => Assert.Equal(new CommentDTO(2, 0, 0,"Very helpful guide for beginners!"), comment),
            comment => Assert.Equal(new CommentDTO(3, 0, 0,"Indeed"), comment),
            comment => Assert.Equal(new CommentDTO(4, 0, 0,"Thank you very much!"), comment));
    }

    [Fact]
    public async Task GetAll_Returns_Empty_List_For_Non_existing_Comments()
    {
        var actual = await _repo.GetAll();

        var expected = new ReadOnlyCollection<CommentDTO>(new Collection<CommentDTO>());

        expected.Should().BeEquivalentTo(actual);
    }
    
    [Fact]
    public async Task Push_creates_new_comment_with_autogenerated_id_and_written_content()
    {
        var comment = new CommentCreateDTO() {Content = "Nice Video!"};

        var actual = await _repo.Push(comment);
        
        Assert.Equal(1, actual.Id);
        Assert.Equal("Nice Video!", actual.Content);
    }
    
    [Fact]
    public async Task Get_returns_Comment_for_given_id()
    {
        var category = new CommentCreateDTO() {Content = "A simple comment"};

        await _repo.Push(category);

        var expected = new CommentDTO(1, 0, 0,"A simple comment");

        var actual = await _repo.Get(1);
        
        Assert.Equal(expected, actual);
    }

    [Fact]
    public async Task Get_returns_null_for_non_existing_id()
    {
        var comment = await _repo.Get(4);
        
        Assert.Null(comment);
    }

    [Fact]
    public async Task Get_Returns_Creator()
    {
        var user = new User() {Id = 1, Name = "SødFisk", Comments = new List<Comment>()};

        await _context.Users.AddAsync(user);

        var comment = new CommentCreateDTO() {CreatedBy = 1, Content = "This comment is created by SødFisk"};

        await _repo.Push(comment);

        var actual = new User();

        
        foreach (var commenter in _context.Users)
        {
            if (commenter.Id == comment.CreatedBy)
            {
                actual = commenter;
            }
        }
        Assert.Equal(actual, user);
    }


    [Fact]
    public async Task Update_of_existing_comment_returns_StateUpdated()
    {
        var comment = new CommentCreateDTO() {Content = "This is an awesome project!"};

        await _repo.Push(comment);

        var update = new CommentUpdateDTO() {Id = 1, Content = "Yes, i mean it's crazy!"};

        var actual = await _repo.Update(update);
        
        Assert.Equal(Status.Updated, actual);
    }

    [Fact]
    public async Task Update_returns_NotFound_for_non_existing_category()
    {
        var update = new CommentUpdateDTO() {Id = 10, Content = "Am i trying to change an non-existing comment?"};

        var response = await _repo.Update(update);
        
        Assert.Equal(Status.NotFound, response);
    }

    [Fact]
    public async Task Update_changes_content_of_comment_of_givenID()
    {
        var comment = new CommentCreateDTO() {Content = "Awesome tutorial!"};

        await _repo.Push(comment);

        var update = new CommentUpdateDTO() {Id = 1, Content = "Maybe it wasn't that good"};

        await _repo.Update(update);

        var expected = new CommentDTO(1, 0, 0, "Maybe it wasn't that good");

        var actual = await _repo.Get(1);
        
        Assert.Equal(expected, actual);
    }
    
}