global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Identity.Web;
global using Microsoft.Identity.Web.Resource;
global using VideoOverflow.Core;
global using VideoOverflow.Infrastructure;
global using static VideoOverflow.Core.Status;
global using VideoOverflow.Core.DTOs;
global using VideoOverflow.Core.IRepositories;
global using VideoOverflow.Server.Model;