global using Microsoft.Data.Sqlite;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Data.Sqlite;
global using Microsoft.EntityFrameworkCore;
global using Xunit;
global using VideoOverflow.Core;
global using VideoOverflow.Infrastructure;
global using Server;
global using Xunit;
global using Microsoft.Extensions.Logging;       
global using Moq;                                
global using Server.Controllers;                 
global using VideoOverflow.Core.DTOs;
global using System.Collections.ObjectModel;
global using Microsoft.AspNetCore.Mvc;
global using VideoOverflow.Core;
global using VideoOverflow.Core.IRepositories;
global using static VideoOverflow.Core.Status;
