name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5002:5432

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName!~VideoOverflow.Server.Integration.Tests"
    - name: Test Infrastructure
      working-directory: ./VideoOverflow.Infrastructure.Tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='./result.xml' --no-restore --verbosity normal
    - name: Test Server
      working-directory: ./VideoOverflow.Server.Tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='./result.xml' --no-restore --verbosity normal
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        file: ./VideoOverflow.Server.Tests/result.xml
        flags: unittests
        fail_ci_if_error: true
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        file: ./VideoOverflow.Infrastructure.Tests/result.xml
        flags: unittests
        fail_ci_if_error: true
