name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5002:5432

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName!~VideoOverflow.Server.Integration.Tests"
    
    - name: Test Infrastructure
      run: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:CoverletOutput=TestResults/ --no-restore --verbosity normal VideoOverflow.Infrastructure.Tests/
      
    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: Unit Test Coverage
        color: brightgreen
        path: VideoOverflow.Infrastructure.Tests/TestResults/coverage.opencover.xml
        gist-filename: code-coverage.json
        gist-id: 0429939e94ea4bf60727cef5e69faa60
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}
